//! Git commit integration for analysis results

use std::path::Path;
use std::process::Command;

/// Commit quality metrics to git
pub struct GitCommitter {
    repo_path: PathBuf,
    author_name: String,
    author_email: String,
}

impl GitCommitter {
    pub fn new(repo_path: impl AsRef<Path>) -> Self {
        Self {
            repo_path: PathBuf::from(repo_path.as_ref()),
            author_name: "fleet-spread".to_string(),
            author_email: "fleet-spread@localhost".to_string(),
        }
    }

    pub fn with_author(mut self, name: &str, email: &str) -> Self {
        self.author_name = name.to_string();
        self.author_email = email.to_string();
        self
    }

    /// Stage a file
    pub fn add(&self, path: impl AsRef<Path>) -> Result<(), GitError> {
        let path = path.as_ref();
        let full_path = if path.is_absolute() {
            path.to_path_buf()
        } else {
            self.repo_path.join(path)
        };

        self.run(&["add", full_path.to_str().unwrap()])?;
        Ok(())
    }

    /// Create a commit with a message
    pub fn commit(&self, message: &str) -> Result<String, GitError> {
        // Configure git author
        self.run(&["config", "user.name", &self.author_name])?;
        self.run(&["config", "user.email", &self.author_email])?;

        // Commit
        self.run(&["commit", "-m", message])?;

        // Get commit hash
        let output = self.run_with_output(&["rev-parse", "HEAD"])?;
        Ok(output.trim().to_string())
    }

    /// Get the current branch name
    pub fn current_branch(&self) -> Result<String, GitError> {
        let output = self.run_with_output(&["rev-parse", "--abbrev-ref", "HEAD"])?;
        Ok(output.trim().to_string())
    }

    /// Check if there are uncommitted changes
    pub fn has_changes(&self) -> Result<bool, GitError> {
        let output = self.run_with_output(&["status", "--porcelain"])?;
        Ok(!output.trim().is_empty())
    }

    /// Get the status of the working tree
    pub fn status(&self) -> Result<String, GitError> {
        let output = self.run_with_output(&["status"])?;
        Ok(output)
    }

    fn run(&self, args: &[&str]) -> Result<(), GitError> {
        let output = self.run_with_output(args)?;
        if !output.is_empty() && !args[0].eq("status") {
            tracing::debug!("git {}: {}", args[0], output.trim());
        }
        Ok(())
    }

    fn run_with_output(&self, args: &[&str]) -> Result<String, GitError> {
        let output = Command::new("git")
            .args(args)
            .current_dir(&self.repo_path)
            .output()
            .map_err(|e| GitError::CommandFailed(args.join(" "), e.to_string()))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(GitError::NonZeroExit(args.join(" "), output.status.code().unwrap_or(-1), stderr.to_string()));
        }

        Ok(String::from_utf8_lossy(&output.stdout).to_string())
    }
}

#[derive(Debug)]
pub enum GitError {
    CommandFailed(String, String),
    NonZeroExit(String, i32, String),
}

impl std::fmt::Display for GitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            GitError::CommandFailed(cmd, e) => write!(f, "git command failed: {} - {}", cmd, e),
            GitError::NonZeroExit(cmd, code, stderr) => write!(f, "git {} exited {}: {}", cmd, code, stderr),
        }
    }
}

impl std::error::Error for GitError {}

/// Generate a commit message for analysis results
pub fn generate_commit_message(
    graph_id: &str,
    robust_count: usize,
    tension_count: usize,
    blind_spot_count: usize,
    synthesis_gain: f64,
) -> String {
    let mut msg = format!(
        "fleet-spread analysis: {}

## Summary
- Robust findings: {}
- Tensions: {}
- Blind spots: {}
- Synthesis gain: {:.2}

",
        graph_id,
        robust_count,
        tension_count,
        blind_spot_count,
        synthesis_gain
    );

    if synthesis_gain > 0.5 {
        msg.push_str("## Analysis Quality\n");
        msg.push_str("High synthesis gain indicates the combined analysis adds substantial value over individual specialists.\n");
    } else if synthesis_gain < 0.1 {
        msg.push_str("## Analysis Quality\n");
        msg.push_str("Low synthesis gain suggests specialists largely overlap. Consider adding specialized analysis dimensions.\n");
    }

    msg.push_str("\nGenerated by fleet-spread\n");
    msg
}

/// Check if git is available
pub fn git_available() -> bool {
    Command::new("git").arg("--version").output().is_ok()
}

use std::path::PathBuf;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_commit_message_generation() {
        let msg = generate_commit_message("test-graph", 5, 2, 3, 0.42);
        assert!(msg.contains("test-graph"));
        assert!(msg.contains("Robust findings: 5"));
        assert!(msg.contains("Synthesis gain: 0.42"));
    }
}
